// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _1215EFCoreShopApp.Data;

namespace _1215EFCoreShopApp.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20211223193113_bring-it-back-again")]
    partial class bringitbackagain
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("_1215EFCoreShopApp.Models.Shop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Shops");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsDeleted = false,
                            Name = "Electronics"
                        },
                        new
                        {
                            Id = 2,
                            IsDeleted = false,
                            Name = "Groceries"
                        });
                });

            modelBuilder.Entity("_1215EFCoreShopApp.Models.ShopItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("ShopId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ShopId");

                    b.ToTable("ShopItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ExpiryDate = new DateTime(2021, 12, 23, 19, 31, 13, 65, DateTimeKind.Utc).AddTicks(2881),
                            IsDeleted = false,
                            Name = "Phone",
                            ShopId = 1
                        },
                        new
                        {
                            Id = 2,
                            ExpiryDate = new DateTime(2021, 12, 23, 19, 31, 13, 65, DateTimeKind.Utc).AddTicks(3266),
                            IsDeleted = false,
                            Name = "Bread",
                            ShopId = 2
                        },
                        new
                        {
                            Id = 3,
                            ExpiryDate = new DateTime(2021, 12, 23, 19, 31, 13, 65, DateTimeKind.Utc).AddTicks(3271),
                            IsDeleted = false,
                            Name = "TV",
                            ShopId = 1
                        },
                        new
                        {
                            Id = 4,
                            ExpiryDate = new DateTime(2021, 12, 23, 19, 31, 13, 65, DateTimeKind.Utc).AddTicks(3273),
                            IsDeleted = false,
                            Name = "Milk",
                            ShopId = 2
                        },
                        new
                        {
                            Id = 5,
                            ExpiryDate = new DateTime(2021, 12, 23, 19, 31, 13, 65, DateTimeKind.Utc).AddTicks(3276),
                            IsDeleted = false,
                            Name = "Beef",
                            ShopId = 2
                        });
                });

            modelBuilder.Entity("_1215EFCoreShopApp.Models.ShopItemTag", b =>
                {
                    b.Property<int>("TagId")
                        .HasColumnType("int");

                    b.Property<int>("ShopItemId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.HasKey("TagId", "ShopItemId");

                    b.HasIndex("ShopItemId");

                    b.ToTable("ShopItemTags");
                });

            modelBuilder.Entity("_1215EFCoreShopApp.Models.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Tags");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsDeleted = false,
                            Name = "Free Shipping"
                        },
                        new
                        {
                            Id = 2,
                            IsDeleted = false,
                            Name = "Cheap"
                        },
                        new
                        {
                            Id = 3,
                            IsDeleted = false,
                            Name = "Brand"
                        });
                });

            modelBuilder.Entity("_1215EFCoreShopApp.Models.ShopItem", b =>
                {
                    b.HasOne("_1215EFCoreShopApp.Models.Shop", "Shops")
                        .WithMany("ShopItems")
                        .HasForeignKey("ShopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Shops");
                });

            modelBuilder.Entity("_1215EFCoreShopApp.Models.ShopItemTag", b =>
                {
                    b.HasOne("_1215EFCoreShopApp.Models.ShopItem", "ShopItem")
                        .WithMany("ShopItemTags")
                        .HasForeignKey("ShopItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("_1215EFCoreShopApp.Models.Tag", "Tag")
                        .WithMany("ShopItemsTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ShopItem");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("_1215EFCoreShopApp.Models.Shop", b =>
                {
                    b.Navigation("ShopItems");
                });

            modelBuilder.Entity("_1215EFCoreShopApp.Models.ShopItem", b =>
                {
                    b.Navigation("ShopItemTags");
                });

            modelBuilder.Entity("_1215EFCoreShopApp.Models.Tag", b =>
                {
                    b.Navigation("ShopItemsTags");
                });
#pragma warning restore 612, 618
        }
    }
}
