// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _1215EFCoreShopApp.Data;

namespace _1215EFCoreShopApp.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20211216162435_added-relationship")]
    partial class addedrelationship
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("_1215EFCoreShopApp.Models.Shop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Shops");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Electronics"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Groceries"
                        });
                });

            modelBuilder.Entity("_1215EFCoreShopApp.Models.ShopItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ShopId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ShopId");

                    b.ToTable("ShopItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ExpiryDate = new DateTime(2021, 12, 16, 16, 24, 34, 606, DateTimeKind.Utc).AddTicks(755),
                            Name = "Phone",
                            ShopId = 1
                        },
                        new
                        {
                            Id = 2,
                            ExpiryDate = new DateTime(2021, 12, 16, 16, 24, 34, 606, DateTimeKind.Utc).AddTicks(1157),
                            Name = "Bread",
                            ShopId = 2
                        },
                        new
                        {
                            Id = 3,
                            ExpiryDate = new DateTime(2021, 12, 16, 16, 24, 34, 606, DateTimeKind.Utc).AddTicks(1161),
                            Name = "TV",
                            ShopId = 1
                        },
                        new
                        {
                            Id = 4,
                            ExpiryDate = new DateTime(2021, 12, 16, 16, 24, 34, 606, DateTimeKind.Utc).AddTicks(1162),
                            Name = "Milk",
                            ShopId = 2
                        },
                        new
                        {
                            Id = 5,
                            ExpiryDate = new DateTime(2021, 12, 16, 16, 24, 34, 606, DateTimeKind.Utc).AddTicks(1163),
                            Name = "Beef",
                            ShopId = 2
                        });
                });

            modelBuilder.Entity("_1215EFCoreShopApp.Models.ShopItem", b =>
                {
                    b.HasOne("_1215EFCoreShopApp.Models.Shop", "Shops")
                        .WithMany("ShopItems")
                        .HasForeignKey("ShopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Shops");
                });

            modelBuilder.Entity("_1215EFCoreShopApp.Models.Shop", b =>
                {
                    b.Navigation("ShopItems");
                });
#pragma warning restore 612, 618
        }
    }
}
